.then 메소드가 어떤 객체를 리턴하는지, Promise 객체라면 해당 객체의 상태, 값은 무엇인지가 헷갈려서 주석으로 최대한 정리 해 봤다.

```
// https://www.error.www라는 URL은 존재하지 않음
// 그러므로 fetch 함수의 작업은 실패함

// Promise 객체 리턴, State: rejected, Value: Error 정보
fetch('https://www.error.www')

  // 두 번째 콜백 함수가 존재하지 않으므로 위와 동일한 Promise 객체 리턴
  .then((response) => response.text())

  // 두 번째 콜백 함수가 존재하지 않으므로 위와 동일한 Promise 객체 리턴
  .then((result) => { console.log(result); })

  // 드디어 error 처리. Hello 출력. 그리고 새로운 에러를 던짐
  // Promise 객체 리턴, State: rejected, Value: Error 정보
  .catch((error) => { console.log('Hello'); throw new Error('test'); })

  // 두 번째 콜백 함수가 존재하지 않으므로 위와 동일한 Promise 객체 리턴
  .then((result) => { console.log(result); })

  // 첫 번째 파라미터가 undefined인 .then 메소드 : .catch 메소드와 동일하다
  // error 처리. 아무 것도 반환하지 않음 (어떠한 수행도 없음)
  // Promise 객체 리턴, State: fulfilled, Value: undefined
  // 아무것도 반환하지 않으면 Promise의 value는 undefined가 된다.
  .then(undefined, (error) => { })

  // 위에서 반환한 Promise 객체의 상태가 fulfilled 이므로 실행되지 않음
  .catch((error) => { console.log('JS'); })

  // 현재 객체의 값인 undefined를 출력한다.
  // Promise 객체 리턴, State: rejected, Value: Undefined
  .then((result) => { console.log(result); })

  // finally 부분은 언제나 실행된다. 콘솔에 final 출력
  .finally(() => { console.log('final'); });

```

결과적으로 콘솔에 출력되는 값은 Hello, Undefined, final 이 세 개가 된다.
